### ISSUE TITLE
Chrome 32, SizeWatcher can't set scroll position of scroll watchers. 

### ISSUE THREAD

**Issue by rrphotosoft** [smnh/FontLoader#16]
Hi,

Great library but unfortunately,
I get this error and it says not all fonts were loaded.
    SizeWatcher can't set scroll position of scroll watchers. 
Im trying to use this with "weathericons". Here's the link to the CDN for the font css file: 
    https://cdnjs.cloudflare.com/ajax/libs/weather-icons/2.0.5/css/weather-icons.css

Best Regards,
Bhargav

**Comment by smnh** [comment]
Hi @rrphotosoft,
In which OS and browser version is it happening,
Also, can you paste a code snippet of how you are trying to load the fonts? Are you setting timeout for example?

**Comment by smnh** [comment]
Here, the unicode character of the "day-cloudy-high" icon is "F07D". Adding it to the `FontLoader.referenceText` should solve the issue:

```HTML
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/weather-icons/2.0.5/css/weather-icons.css">
	<script type="text/javascript" src="FontLoader.js"></script>
</head>
<body>
	<script type="text/javascript">
		FontLoader.referenceText += "\uf07d";
		var fontLoader = new FontLoader(["weathericons"], {
			"fontLoaded": function(font) {
				console.log("font loaded: " + font.family);
			},
			"complete": function(error) {
				if (error !== null) {
					// Reached the timeout but not all fonts were loaded
					console.log(error.message);
					console.log(error.notLoadedFonts);
				} else {
					// All fonts were loaded
					console.log("all fonts were loaded");
				}
			}
		}, 3000);
		fontLoader.loadFonts();
	</script>
</body>
</html>
```

**Comment by heymath** [comment]
@smnh Hi! First, thanks for this library :)
I got this `SizeWatcher can't set scroll position of scroll watchers.` message in console on Safari and Firefox while at the same time I don't get it on Chrome (I'm on Mac).
I'm using this library to load several fonts in a text editor case, so I can not figure the characters out because it can have a lot of fonts used. So I can not really try your previous answer/fix.
But because it works on Chrome I wonder if it is actually the same issue, and if it could fix Firefox and Safari errors anyway ....
Do you have any idea what could make your lib works on Chrome but not other browers? :/

**Comment by smnh** [comment]
Hi @heymath,
Does this error appear for specific fonts you try to load, or for any font?
You can run the tests located in `Tests/compat-tests.html` in Firefox and Safari to see if the FontLoader works for the general case. If these tests are passing successfully (except the 3rd test which should pass only in IE10 and lower), then probably there is a problem with a specific font. Try to use the elimination method to find the problematic font.

**Comment by heymath** [comment]
Hi @smnh, indeed I was in a rush so I just moved to [WebFontLoader](https://github.com/typekit/webfontloader) instead of FontLoader, however thank you for your help.
FYI: I just ran tests in Chrome, Firefox and Safari, and they passed excepted the 3rd as described.
