### ISSUE TITLE
Support font-stretch

### ISSUE THREAD

**Issue by tremby** [smnh/FontLoader#19]
I want to use the third character of FVD, the font-stretch. For example `Din:n4c`, which is normal style, normal weight, condensed. At present I get an error saying that this is not a valid font description.

**Comment by smnh** [comment]
Hi @tremby 

FontLoader does not support the font-stretch and font-variant CSS properties.
Does your `condensed` font defined in a separate font file that the `normal` font?
If not, then you don't need to specify the `condensed` font-stretch value, because as soon as the font will be loaded, all possible font stretches will be loaded altogether.

**Comment by tremby** [comment]
Yes, I know; that's why I'm asking for the feature.

The condensed version is a separate font.
